parameters:
#    cluddy_base.example.class: Cluddy\BaseBundle\Example

services:
#    cluddy_base.example:
#        class: %cluddy_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
