parameters:
#    cluddy_user.example.class: Cluddy\UserBundle\Example

services:
#    cluddy_user.example:
#        class: %cluddy_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
